const products = {
    "3d-black": {
      name: "3d black",
      image: "images/imported/3d-black.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/3d-black.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey","purple-angelo","grey-arbascatto","grey-flurry-georgous-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "albino-gold": {
      name: "albino gold",
      image: "images/imported/albino-gold.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/albino-gold.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-fusion","fantasy-grey", "bracia-beige","grey-flurry-georgous-grey","grey-flurry","grey-arbascatto","forest-blue","marco-polo","pearl-white-2","pearl-white"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "bianco-e-nero": {
      name: "bianco e nero",
      image: "images/imported/bianco-e-nero.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/bianco-e-nero.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["exotic-grey","forest-blue", "grey-william","opera-grey","marco-polo","purple-angelo", "grey-arbascatto", "sarin-collin","statuario-white-3","sentas-exotic"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "bianco-fusion": {
      name: "bianco fusion",
      image: "images/imported/bianco-fusion.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/bianco-fusion.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["albino-gold", "blue-jeans-2", "fantasy-grey","grey-flurry","nsl-black-marble","vanilla-white", "brazillian-blue", "forest-blue","3d-black","pearl-white-2"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "black-marquina-marble": {
      name: "black marquina marble",
      image: "images/imported/black-marquina-marble.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/black-marquina-marble.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["albino-gold", "blue-jeans-2", "bianco-fusion","3d-black","albino-gold","albino-gold", "bianco-e-nero", "bianco-fusion","3d-black","albino-gold"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "blue-jeans-2": {
      name: "blue jeans 2 ",
      image: "images/imported/blue-jeans-2.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/blue-jeans-2.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["albino-gold", "bianco-e-nero", "bianco-fusion","3d-black","albino-gold","albino-gold", "bianco-e-nero", "bianco-fusion","3d-black","albino-gold"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "blue-jeans": {
      name: "blue jeans",
      image: "images/imported/blue-jeans.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/blue-jeans.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "bracia-beige": {
      name: "bracia beige",
      image: "images/imported/bracia-beige.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/bracia-beige.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "brazillian-blue": {
      name: "brazillian-blue",
      image: "images/imported/brazillian-blue.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/brazillian-blue.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "exotic-grey": {
      name: "exotic grey",
      image: "images/imported/exotic-grey.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/exotic-grey.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "fantasy-grey": {
      name: "fantasy grey",
      image: "images/imported/fantasy-grey.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/fantasy-grey.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "forest-blue": {
      name: "forest blue",
      image: "images/imported/forest-blue.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/forest-blue.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "grey-arbascatto": {
      name: "grey arbascatto",
      image: "images/imported/grey-arbascatto.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/grey-arbascatto.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "grey-flurry-georgous-grey": {
      name: "grey flurry georgous grey",
      image: "images/imported/grey-flurry-georgous-grey.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/grey-flurry-georgous-grey.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "grey-flurry": {
      name: "grey flurry",
      image: "images/imported/grey-flurry.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/grey-flurry.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "grey-william": {
      name: "grey william",
      image: "images/imported/grey-william.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/grey-william.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "ice-berg": {
      name: "ice berg",
      image: "images/imported/ice-berg.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/ice-berg.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "marco-polo": {
      name: "marco polo",
      image: "images/imported/marco-polo.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/marco-polo.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "nsl-black-marble": {
      name: "nsl black marble",
      image: "images/imported/nsl-black-marble.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/nsl-black-marble.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "opera-grey": {
      name: "opera grey",
      image: "images/imported/opera-grey.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/opera-grey.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "pearl-white": {
      name: "pearl white",
      image: "images/imported/pearl-white.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/pearl-white.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "pearl-white-2": {
      name: "pearl white 2",
      image: "images/imported/pearl-white-2.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/pearl-white-2.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "purple-angelo-exotic": {
      name: "purple angelo exotic",
      image: "images/imported/purple-angelo-exotic.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/purple-angelo-exotic.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "purple-angelo": {
      name: "purple angelo",
      image: "images/imported/purple-angelo.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/purple-angelo.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "sarin-collin": {
      name: "sarin collin",
      image: "images/imported/sarin-collin.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/sarin-collin.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "sentas-exotic": {
      name: "sentas exotic",
      image: "images/imported/sentas-exotic.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/sentas-exotic.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "statuario-white": {
      name: "statuario white",
      image: "images/imported/statuario-white.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/statuario-white.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "statuario-white-2": {
      name: "statuario white 2",
      image: "images/imported/statuario-white-2.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/statuario-white-2.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "statuario-white-3": {
      name: "statuario white 3",
      image: "images/imported/statuario-white-3.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/statuario-white-3.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "statuario-white-4": {
      name: "statuario white 4",
      image: "images/imported/statuario-white-4.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/statuario-white-4.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    "vanilla-white": {
      name: "vanilla white",
      image: "images/imported/vanilla-white.jpg",
      description: "This stunning Marble is nature’s masterpiece — a perfect choice for those who want to create spaces that leave a lasting impression. Its rich black background, crossed with fine white and golden veins, gives it a bold, dramatic look that speaks of elegance and power. This marble is a statement — of class, taste, and confidence. Marble is one of the foremost choices for interior design by architects and designers.",
      displayImage: "images/imported/display/vanilla-white.png", // Add this property
      specifications: ["thickness","color","Material","surface finish"],
      specifications2: [": 18MM",": Black",": Natural",": polished marble"],
      features: ["Durable", "Easy to Clean", "Glossy Finish","Unique Veins & Patterns","best for indoor"],
      suggestions: ["bianco-e-nero", "black-marquina-marble","blue-jeans","nsl-black-marble", "grey-william", "exotic-grey"],
      usage: [
        { image: "logo/floor.svg", label: "Flooring" },
        { image: "logo/wall cadding.svg", label: "Wall Cadding" },
        { image: "logo/countertop.png", label: "Countertop" },
        { image: "logo/open-door.png", label: "Door Sill" },
        { image: "logo/window.png", label: "Window Jamb" },
        { image: "logo/double-door.png", label: "Door Jamb" },
        { image: "logo/stairs.svg", label: "Stairs" },
      ],
    },
    // add all 100+ products like this
  };
  